### ISSUE TITLE
store.delete issues error

### ISSUE THREAD

**Issue by ckristo** [antoniogarrote/rdfstore-js#105]
When trying to execute store.delete, I get the following error ::
````
/home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/graph_callbacks.js:71
    this.updateInProgress[event].push(quad);
                         ^
TypeError: Cannot read property 'deleted' of null
    at Callbacks.CallbacksBackend.nextGraphModification (/home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/graph_callbacks.js:71:26)
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/query_engine.js:1707:43
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/lexicon.js:440:9
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/utils.js:438:26
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/utils.js:420:9
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/utils.js:401:21
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/utils.js:417:13
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/utils.js:434:21
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/lexicon.js:437:13
    at /home/ckristo/rdfstore-js-example/node_modules/rdfstore/src/utils.js:431:20

Process finished with exit code 1
````

I'm using node.js and the following code:
````javascript
           // - delete existing statements
            var g = rdfEnv.createGraph();
            g.add(rdfEnv.createTriple(me,
                rdfEnv.createNamedNode('foaf:mbox'),
                rdfEnv.createNamedNode('mailto:mail1@example.com')));
            g.add(rdfEnv.createTriple(me,
                rdfEnv.createNamedNode('foaf:mbox'),
                rdfEnv.createNamedNode('mailto:mail2@example.com')));
            store.delete(g, function(arg1, arg2, arg3) {
                console.log(arg1);
                console.log(arg2);
                console.log(arg3);
            });
````

**Comment by antoniogarrote** [comment]
I'm trying to reproduce the error unsuccessfully.

Trying this adapted version of your example:

```js
var Store = require('./src/store');

var frankie = 'http://test.com#francesca';

console.log(Store);

Store.create({name: 'test', overwrite: true}, function (err, store) {

    var graph = store.rdf.createGraph();
    var rdfEnv = store.rdf;


    graph.add(rdfEnv.createTriple(rdfEnv.createNamedNode(frankie),
                              rdfEnv.createNamedNode('foaf:mbox'),
                              rdfEnv.createNamedNode('mailto:mail1@example.com')));
    graph.add(rdfEnv.createTriple(rdfEnv.createNamedNode(frankie),
                              rdfEnv.createNamedNode('foaf:mbox'),
                              rdfEnv.createNamedNode('mailto:mail2@example.com')));


    store.insert(graph, function (err, results) {
        console.log("INSERTING: "+err+" :: "+results);

        store.execute('SELECT * { ?S ?P ?O }', function(err,results){
            console.log(results);
            store.delete(graph, function(err, results){
                console.log("DELETING: "+err+" :: "+results);
                store.execute('SELECT * { ?S ?P ?O }', function(err,results){
                    console.log(results);
                });
            });
        });
    });
});
```

I got a correct result:

```
{ Store: { [Function] VERSION: '0.9.6' },
  create: [Function],
  connect: [Function] }
INSERTING: null :: true
[ { S: { token: 'uri', value: 'http://test.com#francesca' },
    P: { token: 'uri', value: 'http://xmlns.com/foaf/0.1/mbox' },
    O: { token: 'uri', value: 'mailto:mail1@example.com' } },
  { S: { token: 'uri', value: 'http://test.com#francesca' },
    P: { token: 'uri', value: 'http://xmlns.com/foaf/0.1/mbox' },
    O: { token: 'uri', value: 'mailto:mail2@example.com' } } ]
DELETING: null :: true
[]
```
I just run the example directly from current sources. Could you tell me which version of the store are you using?

Also, if you could provide me with a self contained example showing the problem, including the data loading part, I could try to debug it better.

Thanks.

**Comment by ckristo** [comment]
Hi, sure -- here's the link where you can download the complete source of the example: https://www.ckristo.net/owncloud/index.php/s/xurJMhIHAqIjk7c

**Comment by antoniogarrote** [comment]
Hi @ckristo 

I found the problem: you didn't nest the delete operation within the insert and it was causing a problem in the execution of the callbacks.

Since the rewrite, the all modifications in the store are asynchronous, you need to nest the callbacks correctly.

Here's the corrected version: https://gist.github.com/antoniogarrote/8d1fad8df957d090f86c

Cheers.

**Comment by ckristo** [comment]
Hi, ah I see -- so it is not a good idea to start two operations that modify the store in parallel ... thanks!
