### ISSUE TITLE
make.rb tests fails

### ISSUE THREAD

**Issue by fkleedorfer** [antoniogarrote/rdfstore-js#80]
I'm trying to work out a bugfix, but before that I need to get the tests running. Not being a node.js or ruby wizard I might be overlooking something. However, running 
`make.rb tests`
fails with an error. In make.rb I see that src/js-trees/tests/*.js is passed to nodunit. When I execute that directly, I get this output. Other tests fail in a similar manner. Any suggestions?
```
$ ./node_modules/nodeunit/bin/nodeunit ./src/js-trees/tests/

async_disk_manager
✖ testReadWriteNodes

AssertionError: true == false
    at Object.ok (C:\DATA\fkleedorfer\workspace\rdfstore-js\node_modules\nodeunit\lib\types.js:83:39)
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\tests\async_disk_manager.js:39:58
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\src\async_disk_manager.js:197:17
    at Object.wrapper [as oncomplete] (fs.js:465:17)

AssertionError: true == false
    at Object.ok (C:\DATA\fkleedorfer\workspace\rdfstore-js\node_modules\nodeunit\lib\types.js:83:39)
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\tests\async_disk_manager.js:40:58
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\src\async_disk_manager.js:197:17
    at Object.wrapper [as oncomplete] (fs.js:465:17)
AssertionError: true == false
    at Object.ok (C:\DATA\fkleedorfer\workspace\rdfstore-js\node_modules\nodeunit\lib\types.js:83:39)
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\tests\async_disk_manager.js:47:62
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\src\async_disk_manager.js:197:17
    at Object.wrapper [as oncomplete] (fs.js:465:17)

AssertionError: true == false
    at Object.ok (C:\DATA\fkleedorfer\workspace\rdfstore-js\node_modules\nodeunit\lib\types.js:83:39)
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\tests\async_disk_manager.js:47:62
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\src\async_disk_manager.js:197:17
    at Object.wrapper [as oncomplete] (fs.js:465:17)

AssertionError: true == false
    at Object.ok (C:\DATA\fkleedorfer\workspace\rdfstore-js\node_modules\nodeunit\lib\types.js:83:39)
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\tests\async_disk_manager.js:47:62
    at C:\DATA\fkleedorfer\workspace\rdfstore-js\src\js-trees\src\async_disk_manager.js:197:17
    at Object.wrapper [as oncomplete] (fs.js:465:17)

✔ testBufferCache
✔ testDeletionFreeBlocksManager

async_file_backed_b_tree
```

I'm running 
node v0.10.32
ruby 2.1.3p242 (2014-09-19 revision 47630) [x64-mingw32]
inside a fresh install of cygwin-64

btw, the actual bug I think I've fixed is correct handling of typed literals when parsing JSON-LD. The code in rdfstore-js does not conform to the current spec, which uses the '@value' tag, not '@literal'.

**Comment by antoniogarrote** [comment]
Out of date. Use gulp specs now.
